asset_preffix: assets/window
buff: true
logout: true
markers: {menu: menu_marker.png, moon: moon_marker.png, ok: ok.png, select_menu: select_menu.png,
  selected_char_marker: selected_char_marker.png, selector: char_selector_marker.png,
  selector_ok: selector_ok.png, window: window_marker.png}
refresh: true
spawn: false
