asset_preffix: 'assets/window'
markers:
  selector: 'char_selector_marker.png'
  menu: 'menu_marker.png'
  moon: 'moon_marker.png'
  window: 'window_marker.png'
  select_menu: 'select_menu.png'
  selector_ok: 'selector_ok.png'
  ok: 'ok.png'
  selected_char_marker: 'selected_char_marker.png'