# TODO move point such 'enhance' to global scope
enhance:
  cube:
    x: 1
    y: 1
  cycles: 60
#  scope property mean left minimal point for enhance and right maximum point
  scope:
    start:
      - 2
      - 1
    end:
      - 9
      - 11
  max:
    horizontal: 9
    vertical: 11
  points:
    start:
      - 85
      - 85
    enhance:
      - 132
      - 693
    break:
      - 134
      - 628
    clear:
      - 260
      - 605
    combination:
      - 585
      - 440
  delta: 35
combination:
  cell_0:
    - 429
    - 449
  cell_1:
    - 467
    - 448
  one_point:
    - 638
    - 422
  zero_point:
    - 658
    - 442
  enhance:
    - 339
    - 490
  dial_ok:
    - 585
    - 440
