enhancement:
  cube:
    - 9
    - 8
  cycles: 1
recognize:
  prefix:
    path: 'assets/'
    image_suffix: '.png'
  grid:
    image: 'grid_identifier'
    size:
      - 9
      - 11
    eoi: 'end_of_inventory'
  enhance:
    menu: 'enhance_menu'
    slot: 'enhance_main_slot'
    make: 'make_enhance'
# make some images
debug: true