enhancement:
  cube:
    - 4
    - 5
  cycles: 1
recognize:
  prefix:
    path: 'assets/'
    image_suffix: '.png'
  grid:
    image: 'grid_identifier'
    size:
      - 9
      - 11
    eoi: 'end_of_inventory'
# make some images
debug: true