enhancement:
  cube:
    - 8
    - 5
  cycles: 1
recognize:
  prefix:
    path: 'assets/'
    image_suffix: '.png'
  grid:
    image: 'grid_identifier'
    size:
      - 9
      - 11
    eoi: 'end_of_inventory'
  enhance:
    menu: 'enhance_menu'
    slot: 'enhance_main_slot'
    make: 'make_enhance'
    close: 'enhance_close'
  remove:
    menu: 'remove_menu'
    clear: 'clear'
    confirm: 'confirm'
# make some images
debug: true