presets:
  - name: 'esMe_target'
    timings:
      - 2
      - 0.4
      - 0.4
      - 10
      - 14
      - 15
      - 15
      - 30
    actions:
      - '1'
      - '2'
      - '3'
      - ['c', '3']
      - ['c', '1']
      - '5'
      - '6'
      - ['c', '2']
  - name: 'esMe_farming'
    timings:
      - 2
      - 0.4
      - 0.4
      - 10
      - 14
      - 15
      - 15
      - 30
      - 10
      - 10
    actions:
      - '1'
      - '2'
      - '3'
      - ['c', '3']
      - ['c', '1']
      - '5'
      - '6'
      - ['c', '2']
      - '_'
      - 't'
  - name: 'Solution'
    timings:
      - 1
      - 4
      - 5
      - 6
    actions:
      - '1'
      - '2'
      - '3'
      - '_'
  - name: 'Acedia'
    timings:
      - 10
      - 5
      - 1
      - 80
      - 6
    actions:
      - '2'
      - '3'
      - '4'
      - '5'
      - '_'
