presets:
  - name: 'esMe:target'
    timings:
      - 2
      - 0.4
      - 0.4
      - 10
      - 14
      - 15
      - 15
      - 30
    actions:
      - '1'
      - '2'
      - '3'
      # - ['c', '3']
      - '4'
      # - ['c', '1']
      - '5'
      - '6'
      # - ['c', '2']
      - '_'
  - name: 'esMe:farming'
    timings:
      - 2
      - 0.4
      - 0.4
      - 10
      - 60
      - 60
      # - 16
      # - 30
      # - 10
      - 8
    actions:
      - '1'
      - '2'
      - '3'
      # - ['c', '3']
      - '4'
      # - ['c', '1']
      - '5'
      - '6'
      # - ['c', '2']
      - '_'
      # - '1'
      # - '2'
      # - '3'
      # - ['c', '3']
      # - ['c', '1']
      # - '5'
      # - '6'
      # - ['c', '2']
      # - '_'
      # - 't'

  - name: 'Solution'
    timings:
      - 1
      - 4
      - 5
      - 6
    actions:
      - '1'
      - '2'
      - '3'
      - '_'
  - name: 'Acedia'
    timings:
      - 10
      - 5
      - 1
      - 80
      - 6
    actions:
      - '2'
      - '3'
      - '4'
      - '5'
      - '_'
